trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g newman'
  displayName: 'Install Newman'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g newman-reporter-htmlextra'
  displayName: 'Install Newman Reporter HTML Extra'

- task: CmdLine@2
  inputs:
    script: 'newman run Collection/reqres.in_tests.postman_collection.json -e Collection/reqres.postman_environment.json -r cli,html,junit --reporter-junit-export junitReport.xml --reporter-htmlextra-export TestReport.html'
  displayName: 'Run Postman Collection'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'NewmanHTMLReport'
    targetPath: '$(System.DefaultWorkingDirectory)/TestReport.html'
  displayName: 'Publish HTML Report'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junitReport.xml'
  displayName: 'Publish Test Results'

